FROM node:lts-alpine3.21 AS build

ARG VITE_REGISTRY_PROCESS_ID
ENV VITE_REGISTRY_PROCESS_ID=${VITE_REGISTRY_PROCESS_ID}
ARG VITE_PRIMARY_NEST_ID
ENV VITE_PRIMARY_NEST_ID=${VITE_PRIMARY_NEST_ID}
ARG VITE_HYPERBEAM_ENDPOINT
ENV VITE_HYPERBEAM_ENDPOINT=${VITE_HYPERBEAM_ENDPOINT}
ARG VITE_SEARCH_API_URL
ENV VITE_SEARCH_API_URL=${VITE_SEARCH_API_URL}
ARG VITE_WUZZY_SITE_VERSION
ENV VITE_WUZZY_SITE_VERSION=${VITE_WUZZY_SITE_VERSION}

WORKDIR /usr/src/app
COPY . .
RUN apk add --no-cache python3 py3-pip make g++ curl unzip rclone
RUN npm install
RUN npm run build

FROM nginx:1.29.0-alpine
COPY --from=build /usr/src/app/dist /usr/share/nginx/html
